### ISSUE TITLE
Save Button NotWorking

### ISSUE THREAD

**Issue by Nazarii76** [kevinchappell/formBuilder#1050]
Hello
I need Get Html And Save

but Save Button notworking

help me plz

**Comment by kevinchappell** [comment]
can you provide more info and a sandbox of that replicates the problem on either jsfiddle.net, codepen.io or codesandbox.io?

**Comment by jaydev-solanki** [comment]
I am facing similar problem that how can we save values filled up in the controls of rendered form. I mean each user designed form would be different so maintaining it via model would be difficult. It would be great if you have any idea for the same. Thanks.

**Comment by kevinchappell** [comment]
you should be able to use the `userData` now. Can you provide a specific use case? https://formbuilder.online/docs/formRender/actions/userData/

**Comment by zareshahi** [comment]
Hi everyone
Thanks to @kevinchappell for his answer but there is important problem
the save btn disabled and there is no way (except find form id to choose the save btn by its unique id and i don't know each form unique id) to change save btn action or name
in [documentation save section](https://formbuilder.online/docs/formBuilder/actions/save/) we must use external button to save (instead of main save btn :/ ) but there is no result after save form, it's undefined.

how can we use form save button? or another main buttons in bottom of form?

**Comment by kevinchappell** [comment]
@zareshahi https://formbuilder.online/docs/formBuilder/options/onSave/
