### ISSUE TITLE
Multiple in select option: BUG

### ISSUE THREAD

**Issue by nguyendachuy** [kevinchappell/formBuilder#1152]
### Description:
I use the normal builder select but when rendering the HTML it automatically converts name select to array

### Environment Details:

 - formBuilder Version: 3.6.1
 - Browser: Firefox 85.0b4 (64-bit)
 - OS: Windows 10

### Screenshot - *(optional)*
![image](https://user-images.githubusercontent.com/15666602/103434557-b3e46700-4c35-11eb-9bbb-e79472409cd9.png)
![image](https://user-images.githubusercontent.com/15666602/103434563-d2e2f900-4c35-11eb-9536-8d0959647b70.png)

**Comment by KrenZfer** [comment]
Hi,
I use this to fix the that like this,

`// fixAttr
$("[multiple=false]").removeAttr("multiple");
$("[readonly=false]").removeAttr("readonly");`

actually that because our web browser (not all maybe) interpret all select that have multiple attribut even it have false value as multiple select so we have to eliminate that attribute if it has attribute if its value is false,

Let me know if its work for you or not

**Comment by nguyendachuy** [comment]
Your fix can be fixed. But I went back to an older version. Thanks
