### ISSUE TITLE
Idea: Additional CSS support

### ISSUE THREAD

**Issue by sheibeck** [kevinchappell/formBuilder#116]
Currently you have support to add a Class to the input control itself, would you consider allowing Classes to be added to a control's associated label and parent container div? This would pretty much give full control, via bootstrap, to supporting columns and label location (relative to the control).

For example:

```
<div class="form-group COL-MD-6 field-text-input-1458998906140">
        <label class="COL-MD-2 COL-MD-PUSH-8" for="text-input-1458998906140">Text Field  </label>
        <input class="COL-MD-8 COL-MD-PULL-2 form-control" name="text-input-1458998906140" type="text" subtype="text" id="text-input-1458998906140">
</div>
```

My idea would be to put add "Parent Class" and "Label Class" fields alongside the current "Class" field. If that makes sense.

**Comment by kevinchappell** [comment]
yes, this is definitely coming in 2.0. This feature had to be pushed back to version 2 because it requires the new data model but it will be worth the wait. Field edit window will actually get 3 tabs Attrs, Meta, and Layout. Layout allows you to set left or right position and column width. Undecided if I should call Layout "Style" instead and bundle things like Large, Small, X-Small with colors also but regardless, you're on the right track, this feature is definitely coming.

**Comment by sheibeck** [comment]
That sounds great. Thanks Kevin. Love what you're doing!
