### ISSUE TITLE
[Bug]Radio group and select - issue in options while selecting

### ISSUE THREAD

**Issue by AshwiniSirpa** [kevinchappell/formBuilder#1208]
### Description:
Radio group and select - issue in options while selecting, allowing multiple options to select
### Environment Details:

 - formBuilder Version: 3.6.2
 - Browser: Chrome
 - OS: Windows

### Expected Behavior

- at a time only one option should be selected in radio group and select 
- for select, it should allow to delete the second option

### Actual Behavior

- It is allowing to select multiple options but deselect is not working after selecting morethan one option
- for select delete button is provided on second option but not able to delete it

### Steps to Reproduce
go to edit mode of select and radio group -> add multiple options -> select multiple options
### Screenshots
![image](https://user-images.githubusercontent.com/47180388/122765156-d63e6f80-d2bd-11eb-8498-2bd09c5f91d1.png)
![image](https://user-images.githubusercontent.com/47180388/122765213-e9e9d600-d2bd-11eb-8e2a-39666b422636.png)

Comments:
It works well with older versions of formbuilder - before the onAddOption fetaure

**Comment by pvin** [comment]
**Observations**

Yes you are right @AshwiniSirpa 

Issue has been raised in [#687](https://github.com/kevinchappell/formBuilder/issues/687) and fixed in release [PR-842](https://github.com/kevinchappell/formBuilder/pull/842#issue-227187787 ) (version - [2.10.0](https://github.com/kevinchappell/formBuilder/pull/842#issue-227187787))

This fix was available till [3.5.2](https://github.com/kevinchappell/formBuilder/releases/tag/v3.5.2) and removed in [3.6.0](https://github.com/kevinchappell/formBuilder/compare/v3.5.2...v3.6.0)

**Fix:**
For time being i'm rolled back to 3.52 by using [CDN](https://cdnjs.com/libraries/jQuery-formBuilder/3.5.2)

**Code reference**
 
![merge-image](https://user-images.githubusercontent.com/4160460/218156180-882f296d-a73d-4c15-88a7-1e4e0f878607.png)
