### ISSUE TITLE
formRender setData not Work ?? 

### ISSUE THREAD

**Issue by shakilhasan** [kevinchappell/formBuilder#1221]
### Description:
[![image.png](https://files.gitter.im/564880e216b6c7089cbac6e4/1jbE/thumb/image.png)](https://files.gitter.im/564880e216b6c7089cbac6e4/1jbE/image.png)

[](https://formbuilder.online/docs/formRender/actions/setData/)

**Comment by nmase88** [comment]
did you have any joy with this? I've got the same issue

**Comment by kevinchappell** [comment]
There may be some confusion on how `setData` is intended to be used. Nothing will visually change when using `setData`. It's intended to be used when you have many updates, for example when streaming formData changes from a websocket but you want more control over when the template is rendered.

I have updated the documentation to make this clearer. You may want to use `render` instead of `setData`
