### ISSUE TITLE
Some list item controls are missing class.

### ISSUE THREAD

**Issue by haisol** [kevinchappell/formBuilder#1222]
### Description:
I'm writing some customization. I'm having an issue with the demo source code. I haven't gotten latest in a month or so. When adding a 'header' element onto the builder it has a proper class identification but once rendered its identification is gone. Perhaps there are other elements with missing class identifications or maybe this has already been resolved?

<div class="rendered-form">
<div class="">
<label for="undefined" class="formbuilder-header-label">Header</label>
<h1 access="false" id="control-2627650">Header</h1>
</div>
<div class="formbuilder-text form-group field-text-1630327567794-0">
<label for="text-1630327567794-0" class="formbuilder-text-label">Text Field</label>
<input type="text" class="form-control" name="text-1630327567794-0" access="false" id="text-1630327567794-0">
</div>
</div>
### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS: 

### Expected Behavior
all items should have a class
### Actual Behavior
header related items are missing class
### Steps to Reproduce
add a header onto the form and inspect it.  It has a class.  Now render the form and the class is gone.
### Screenshot - *(optional)*
![image](https://user-images.githubusercontent.com/1390339/131595543-da8cff5c-13d2-41b9-8e33-b081d1ffa007.png)

**Comment by lucasnetau** [comment]
If you take a look at layout.js you'll see that the default layout only renders a class for field's that have an ID (field with name). Headers are one of the field types that does not have a name/id because it does not store a value. When in formBuilder/preview mode there is an ID associated with the field hence it renders the className in the wrapper.

layout.js line 4-6:
```
const processClassName = (data, field) => {
  // wrap the output in a form-group div & return
  let className = data.id ? `formbuilder-${data.type} form-group field-${data.id}` : ''
```

You can override this through the layout or layoutTemplates configuration options for formRender

**Comment by Jojoshua** [comment]
Looks like this was resolved
