### ISSUE TITLE
Question: Implementing tabs

### ISSUE THREAD

**Issue by sheibeck** [kevinchappell/formBuilder#125]
Kevin, I'm trying to figure out how to implement tabs on a form and I'm using jquery ui tabs. My current line of thought was to have multiple formBuilder instances running, 1 per tab. But, I can't get formRender() to run more than once. I have it so when I switch tabs I try to run formRender() again on the content in said tab, but it doesn't work. formBuilder() works, but I need to be able to render it.

Do you have any ideas about how I could approach this differently? Or is can I request that formRender be modified to allow formRender() to be re-initialized?

Thanks.

**Comment by kevinchappell** [comment]
Unfortunately it sounds like I'd have to see your code to advise you on this. formRender already has some ability to reinitialize but your use case may need some work around. Are you using the jQuery UI tabs event `activate`? If you call formRender() from there it should re-render. If you have a look at the code for the demo on the site, its calling formRender every time you press the save button.

when you look at the console does it say "Form Rendered" when you expect it to? Unless overwritten, this should be logged when a form is rendered. Without seeing the code I would guess formRender is losing reference to either the source data or the target element. If this is the case you could either re-acquire the target/source (whichever youre losing reference to) OR pass the data directly into the new formRender call. It's undocumented, but you can use formRender like this: [demo](http://codepen.io/kevinchappell/pen/bprXzw?editors=1010)

In that demo you'll see formRender is actually called on the *target* instead of the source because we are passing the data through config instead of reading it from source element/textarea.

Thinking more about your use case, I would create a data map for the builder in each tab. Then you could hook into the `activate` event and reinit formRender with the data for the appropriate mapping. This way you can keep a single formRender instance and just reinit with the data from the active tab.

**Comment by sheibeck** [comment]
I am using the activate event. http://codepen.io/sheibeck/pen/VazBGX

The event fires, but always seems to render "#fb-template-0" even if I pass
in "#fb-template-1".  Regardless, mapping to the config setting, as you
suggested, sounds like the way I should be doing it.

Thanks for taking the time to respond, I'll try the config setting and see
if that works better. Which it sounds like it should.

**Comment by kevinchappell** [comment]
@sheibeck How did you make out on this issue? 

I'm closing this issue as it's not directly a problem with formBuilder or formRender but I'd still like to know the outcome as your use case sounds like it might make an interesting demo.

**Comment by sheibeck** [comment]
I got it to work with only 2 issues.
1. On formRender() it doesn't hide the <form-template> when I switch tabs.
But, the bigger issue is:
2. When I switch to formBuilder() and try to add and save controls it eventually gets confused and starts to just show one tabs data. Is formBuilder() targeting a specific control ID that gets auto created? 

http://codepen.io/sheibeck/pen/VazBGX

**Re-creation steps:**
1. Switch to Tab2 and add a control, then click save
2. Switch to Tab1 and add a control, then click save
3. Switch back to Tab2, the content still shows Tab1 data.

**Comment by kevinchappell** [comment]
I got it working by calling formBuilder only once. formBuilder should only need to be reinitialized when you are changing it's options. http://codepen.io/kevinchappell/pen/ZWaGqq?editors=1010

But I did find another bug related to the field edit toggle id I'll be looking into.

**Comment by sheibeck** [comment]
Awesome! Looks like there was a class you added in as well that was important: form-builder-template.

Thanks Kevin

**Comment by kevinchappell** [comment]
It could have been any class or selector, its just to call `formBuilder` on an array of jQ wrapped elements. I'll have a fix for the other bug shortly.
