### ISSUE TITLE
Issue with radio groups

### ISSUE THREAD

**Issue by tostis005** [kevinchappell/formBuilder#1317]
### Description:

When you are configuring a radio group field, if you check another option the previous checked option remains checked, you can't check a default option if is not the first option

### Environment Details:

 - formBuilder Version: last version
 - Browser: 
 - OS: 

### Expected Behavior

When checking an option, other options remains unchecked

### Screenshot - *(optional)*

![image](https://user-images.githubusercontent.com/23707815/178445757-6b940844-ac6e-4c7e-b568-274eced468d0.png)

**Comment by pvin** [comment]
**Observations**

Issue has been raised in [#687](https://github.com/kevinchappell/formBuilder/issues/687) and fixed in release [PR-842](https://github.com/kevinchappell/formBuilder/pull/842#issue-227187787 ) (version - [2.10.0](https://github.com/kevinchappell/formBuilder/pull/842#issue-227187787))

This fix was available till [3.5.2](https://github.com/kevinchappell/formBuilder/releases/tag/v3.5.2) and removed in [3.6.0](https://github.com/kevinchappell/formBuilder/compare/v3.5.2...v3.6.0)

**Fix:**
For time being i'm rolled back to 3.52 by using [CDN](https://cdnjs.com/libraries/jQuery-formBuilder/3.5.2)

**Code reference**
 
![merge-image](https://user-images.githubusercontent.com/4160460/218156180-882f296d-a73d-4c15-88a7-1e4e0f878607.png)

**Comment by tostis005** [comment]
thanks!
