### ISSUE TITLE
formRender options - setData does not work

### ISSUE THREAD

**Issue by ArjunDosajh** [kevinchappell/formBuilder#1372]
### Screenshot
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/92713906/232308369-654db495-7b26-4421-b6fd-214ceb19ee4d.png">

**Comment by jseguraweb** [comment]
hello, do you have any news on this? Thanks!

**Comment by asimp51** [comment]
var formData = '[{"type":"text","label":"Full Name","subtype":"text","className":"form-control","name":"text-1476748004559"},{"type":"select","label":"Occupation","className":"form-control","name":"select-1476748006618","values":[{"label":"Street Sweeper","value":"option-1","selected":true},{"label":"Moth Man","value":"option-2"},{"label":"Chemist","value":"option-3"}]},{"type":"textarea","label":"Short Bio","rows":"5","className":"form-control","name":"textarea-1476748007461"}]';

     var formRenderOptions =  {formData} ;
     $('#fb-editor').formBuilder('setData', $('#fb-editor').formRender(formRenderOptions))

Hope this will help !

**Comment by lucasnetau** [comment]
The linked documentation https://formbuilder.online/docs/formRender/actions/setData/ fails use to 404 error on old jQuery library

**Comment by lucasnetau** [comment]
Stepping through the codepen, the initial call to formRender has no formData set (see "No form data." output to console) and therefore doesn't create a formRender instance. Further setData calls will fail silently due to the check ` if (methods.instance) {...}`

**Comment by lucasnetau** [comment]
@kevinchappell Went down a bit of a rabbit hole looking at this one. The demo for this is strange https://formbuilder.online/docs/formRender/actions/setData/ since it wouldn't show any visible changes since setData doesn't render. However that led me to find:

### Issue 1
If formRender is initialised without formData being set or if formData is set to a falsey value (false or '') then the formRender instance is not created

https://github.com/kevinchappell/formBuilder/blob/64dfde5961d867d8ac4156eb967b95b3af94d675/src/js/form-render.js#L74-L77

Any further calls to setData will fail silently due to no instance. Calls to render will throw an Uncaught TypeError due to no container existing

```
form-render.min.js:2 Uncaught TypeError: e.emptyContainer is not a function
    at ae.render (form-render.min.js:2:76722)
    at HTMLDivElement.<anonymous> (form-render.min.js:2:79160)
    at Function.each (jquery-3.5.1.min.js:2:2976)
    at S.fn.init.each (jquery-3.5.1.min.js:2:1454)
    at S.fn.init.render (form-render.min.js:2:79140)
    at e.fn.formRender (form-render.min.js:2:79363)
    at form_render_setdata.html:40:20
```

So the demos on https://formbuilder.online/docs/formRender/actions/render/ and https://formbuilder.online/docs/formRender/actions/setData/ don't work.

### Issue 2
Also this bit of code doesn't do anything because it never assigned rendered to `formRender.markup`

https://github.com/kevinchappell/formBuilder/blob/64dfde5961d867d8ac4156eb967b95b3af94d675/src/js/form-render.js#L236-L241

### Issue 3
And one final strange item, the docs refer to being able to call methods on the formRenderInstance returned by $.formRender however there is no support in the code for that so the examples don't work

```javascript
const formRenderInstance = $('#render-container').formRender(formRenderOptions);
const html = formRenderInstance('html');
//Throws Uncaught TypeError: formRenderInstance is not a function

formRenderInstance.actions.render(formData)
//Throws Uncaught TypeError: Cannot read properties of undefined (reading 'render')
```

### Suggested fixes
* Set formData to empty array in the constructor if falsey
* Remove No form data code since it will now be a dead leg and didn't work anyway
* Update docs to only use `$(container).formBuilder('<method>', ...options)` only

**Comment by kevinchappell** [comment]
@lucasnetau those all sound like good fixes. i think over the years some parts of the api changed that must have broken the functionality here. i recall switching to the jquery plugin recommended syntax for methods because of an issue with `instance.actions.*` methods not working with multiple instances, i think i missed the formRender cleanup.
