### ISSUE TITLE
Remove Name option while drop text field

### ISSUE THREAD

**Issue by rishab-php-digi** [kevinchappell/formBuilder#1379]
### Description:
Hi, I want to remove name option while drop text field, textarea. need to give name as static one, so that i can submit that form with given name. 
### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS:

**Comment by lucasnetau** [comment]
You can hook into the onAdd events and hide the name field wrap and set a static name value. You can also modify the value after a getData call before saving

Since you are building the form through formBuilder there isn't much utility hardcoding a name for a text field as this would prevent any further text fields from being created.

**Comment by prakomkumham** [comment]
Hello, I also have a similar case.

I want the 'name' column to be immutable (disabled) so that I can capture the value of 'name' if there are changes to the values in the other fields. How to modify it?

**Comment by lucasnetau** [comment]
If you take a look at the demo https://kevinchappell.github.io/formBuilder/

The name attribute is disabled on all controls via the config `disabledAttrs: ["name"],`

The name is therefore autogenerated on insert and cannot be edited. Is this what you are after?

If you want certain fields to have a fixed name, you can do this via inputSets with a single field with the name attribute populated

```javascript
inputSets: [
{
  icon: '✅',
  label:  'Fixed Name Demo',
  name: 'fixed-name-control',
  showHeader: false,
  fields: [
    {
      "type": "text",
      "label": "This field has a fixed name of fixed-name",
      "access": false,
      "name":'fixed-name',
    },
  ],
}
],
```

**Comment by prakomkumham** [comment]
Thanks @lucasnetau for your quick response. But what I want is still enable the 'name' field. But as html input tag on 'name' field are any way to add 'disabled' property?

For example:

`<input name="name" placeholder="" class="fld-name form-control" id="name-frmb-1694662305478-fld-1" value="select-1694662308549-0" type="text" disabled>`

I still need the name value, but I don't want the user modified the autogenerated value name field, because I need it for tracking on changing.

Thanks

**Comment by lucasnetau** [comment]
className and name are two special attributes in that there is no way to disable them. When you set these two

**Comment by prakomkumham** [comment]
Okay @lucasnetau, maybe I found the force way using typeUserEvents attribute.

```
typeUserEvents: {
            select: {
                onadd: function () {
                    $("input[name=name]").attr("disabled","disabled");
                }
            },
```

I know its not the best way but I enough that's all.

Thanks for your quick response.

**Comment by lucasnetau** [comment]
Yes you can do it that way too. Personally I find that is a messy view showing the input but making it disabled, however formBuilder does have multiple ways to achieve a goal.
