### ISSUE TITLE
Assigning attr values in control plugin

### ISSUE THREAD

**Issue by hipy** [kevinchappell/formBuilder#1488]
I'm trying to build a custom control plugin, but I run into some difficulty prefilling the various options of the element:

![image](https://github.com/kevinchappell/formBuilder/assets/1358013/dea7070f-ba99-47b5-bfe3-60cab5c95a4d)

I want to prefill the class with 'form-control', but assigning the value in this.config in build() only results in the value being overwritten during rendering. What is the correct way of doing this?

Class I build:
```
// configure the class for runtime loading
if (!window.fbControls) window.fbControls = new Array();
window.fbControls.push(function (controlClass) {

    class controlStarRating extends controlClass {

        static get definition() {
            return {
                i18n: {
                    default: 'salary',
                }
            }
        }

        /**
         * build a text DOM element, supporting other jquery text form-control's
         * @return DOM Element to be injected into the form.
         */
        build() {
            // Assign value, but this does not prefill the field
            this.config.className = "form-control test"
            return this.markup('input', null, {id: this.config.name, className: this.config.class});
        }

        onRender() {
           /// todo
        }
    }

    // register this control for the following types & text subtypes
    controlClass.register('salary', controlStarRating)
    controlClass.register('salary', controlStarRating, 'salary')
    return controlStarRating;
});
```

**Comment by lucasnetau** [comment]
Hi @hipy 

build() is called when building the form element and onRender once it is constructed. In formBuilder these two are called regularly to update the preview anytime the field attribures are modified. So the don't have any relation to the attributes in the edit panel.

You can define default values via setting a defaultAttrs value in the control definition or by defining the field via the fields or replaceFields config options.

```javascript
    static get definition() {
            return {
                i18n: {
                    default: 'salary',
                },
                defaultAttrs: {
                    'className': {
                        label: "Class",
                        value: 'form-control',
                        type: 'text',
                    },
            }
        }
```

Saying that, if your control requires the form-control class then you can just append it to className in the build() stage like you are doing already. I do this for many of my custom controls so that form editors cannot accidentally remove a required class.

**Comment by hipy** [comment]
That helped me out. Thank you!
