### ISSUE TITLE
setData formRender

### ISSUE THREAD

**Issue by FelipeEspinozaMe** [kevinchappell/formBuilder#1513]
### Description: setData example in code pen and code example doesnt seem to work as espected, the code pen does nothing at changing the options when using it.
how should i use setData when rendering?

**Comment by lucasnetau** [comment]
Thank you for your report.

The bug was fixed in v3.16.2, so the code will work if you try locally with your own copy of the library.

https://formbuilder.online/docs/formBuilder/actions/setData/ worked correctly in Chrome, Firefox and Safari when tested.

https://formbuilder.online/docs/formRender/actions/setData/ still showing an issue. It is loading an old version of FormBuilder

@kevinchappell can you please update https://codepen.io/kevinchappell/pen/MWrgyJV to remove the hard-coded version string of formBuilder (loading 3.7.3)
