### ISSUE TITLE
2.0 Roadmap questions

### ISSUE THREAD

**Issue by larowlan** [kevinchappell/formBuilder#152]
Hi
I'm working on building integration with Drupal 8 for the plugin.
My goal is to build a prototype of simplifying Drupal's Field UI using this plugin. Along the lines of a broader approach to changes in site building for Drupal (http://buytaert.net/handling-context-in-outside-in).
I see in a couple of places in this library's issue queue the mention of a 2.0 alpha.

I have a couple of questions:

- Is there a roadmap for 2.0 - e.g. what's coming, timelines, remaining tasks
- Should I hold off and use 2.0 instead? I'm intending to make the system pluggable (as is the norm for Drupal) and I see mention of changes to how field-types/components are registered in some threads regarding 2.0 version.
- Is there anything I can do to help move the 2.0 branch along, keen to pitch in.

Thanks

Lee

**Comment by kevinchappell** [comment]
Hey Lee,
- There isn't a clearly defined roadmap and since this is a side project its a bit difficult to stick to hard dates. The alpha that's been mention here and there is pretty close to shipping though.
- It definitely worth waiting for the next version for a Drupal integration as v1 is pretty limited in field configuration.
- As for helping I'm sure a number of issues will be filed against the alpha release and would really appreciate them being addressed.

In the meantime I'll leak another gif- this time of what manual column editing looks like. There will of course be preset options but they are not pictured here.
![stage-preview](https://cloud.githubusercontent.com/assets/1457540/15454545/8c13c5b4-2033-11e6-8fa0-02141bbee783.gif)

**Comment by larowlan** [comment]
Hi Kevin

- Thanks, appreciate this is done in spare time so no firm dates.
- Will definitely wait - one thing I could start on now - does the XML schema change much?
- Sure, will help with issues after alpha

Dual columns feature looks great. For Drupal it would be awesome to support details w/ summary and fieldset w/ legend so seeing the two-column support is great, indicates there is a nested structure already.

Thanks again for taking the time to answer my questions.

Lee

**Comment by kevinchappell** [comment]
Hey Lee, 
The XML is the bad news. The data schema has completely changed and will require an extra plug-in to edit old forms. In fact, to save time I focused only on JSON in the new version but it wouldn't be difficult to add xml later.

The columns can comfortably support up to 5 columns but editing field data becomes cramped with more than that. I'll probably make field edit panel a modal when there are more than 5 columns. Also you're spot on with the fieldset and legend guess. Those are options in the column edit panel.

**Comment by larowlan** [comment]
No worries, json is better than XML anyway.
