### ISSUE TITLE
If i give large Text for header component in my form builder, UI is getting disrupted. There is no way to limit the length as header component does not p

### ISSUE THREAD

**Issue by hidayathBR** [kevinchappell/formBuilder#1524]
### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS: 

### Screenshot - *(optional)*
![headdeerrr](https://github.com/kevinchappell/formBuilder/assets/153521501/0adf1dc7-8430-43d4-ac5c-cf484b67eb17)

**Comment by lucasnetau** [comment]
FormBuilder doesn't try to get in the way of valid inputs. To restrict the max length for labels you should either hook into the onAddField event and add a maxlen attribute to the input (if HTML labels are disabled), or you need to write a function that limits the number of characters into the div[contenteditable].

On the display side, this can be fixed with CSS, either hiding the overflow or wrapping the header.

```css
    overflow: hidden;
    word-wrap: break-word;
```

I'll take a look whether it makes sense to set one of these by default on the stage.
