### ISSUE TITLE
When Double-click trumbowyg  area will open the Edit issue

### ISSUE THREAD

**Issue by ShingZtore** [kevinchappell/formBuilder#1584]
### Description:
When I set 
`fields : [{
        label: "html",
        id: "htmlTextArea",
        type: "trumbowyg",
    }]`
    And
    `disabledFieldButtons: {
                trumbowyg: ['edit'] // disables the edit button for select fields
              },`
### Environment Details:

 - formBuilder Version: latest version
 - Browser: Chrome
 - OS: Window 10

### Expected Behavior
Double click anywhere should not open the Edit.

### Actual Behavior
Double-click trumbowyg plugin auto open the Edit.

### Screenshot - *(optional)*
![image](https://github.com/user-attachments/assets/6d0b77eb-db83-4bd9-8449-386a8423ea16)
![image](https://github.com/user-attachments/assets/ed3b62aa-ec64-43be-adad-0f20e0190f07)

**Comment by lucasnetau** [comment]
Disabling the edit button doesn't disable the edit panel opening on double click. The current dblClick event handler only targets contenteditable and a few element types to allow you to double click within the content editable box.

If you want to block all editing then look at hooking into the onAddFieldAfter event and set a dblClick handler on the .trumbowyg class to prevent propagating the event (currently $stage.on('dblclick', 'li.form-field') is where the event bubbles up to in order to open the edit field) or remove that event handler

**Comment by ShingZtore** [comment]
Thank you!

I share my solution:

```
$('li.trumbowyg-field').on('dblclick', function(event) {
    event.stopPropagation();
});
```

**Comment by lucasnetau** [comment]
Thank you. Closing.

**Comment by V1pr** [comment]
> Thank you. Closing.

IMHO this should be noted in the docs - that disabling "edit" is not enough for all types of elements.
