### ISSUE TITLE
Having issues with the checkGroup checkbox. not able to select last checkbox

### ISSUE THREAD

**Issue by akashvora** [kevinchappell/formBuilder#1593]
### Description:
Having issues with the checkGroup checkbox. not able to select last checkbox.
When a form is created (with the first checkbox checked by default) with form-renderer and form-builder and saved it using the GetJson() method. 
and submitted the form with different options, facing the issue of not being able to select the last checkbox option.
If you select all the checkboxes, then submit the form and get the submitted response and render it on the form, then only it will get selected if I have selected the last option.

1) If you select and submit all 3 checkbox options, then it's working; using the response when filling up/rendering the form is working.
2) If you select the middle (second) checkbox and the third (last) checkbox and submit and render, the last checkbox does not get selected.
2) If you select the first checkbox and the third (last) checkbox and submit and render, the last checkbox does not get selected.

### Environment Details:

 - formBuilder Version: 3.19.13 (upgraded from 3.6.1 as facing the issue 1518 => https://github.com/kevinchappell/formBuilder/issues/1518 )
 - Browser: Chrome
 - OS: Windows 11

### Expected Behavior
If I select the last checkbox and others deselected, then only the last option should be selected from the last response. Currently.

### Actual Behavior
If I select all 3 options, then only the last option is passed/submitted with selected:true and gets selected on the next render.

### Steps to Reproduce
drag and drop multiple controls like radioGroup and checkgroup.
In the checkbox group, add 3 options.
Keep the 1st option selected and the other deselected, and fill the value checkbox of the first checkbox and keep the value of the remaining checkbox's value empty.
Render the form.
Deselect the first checkbox and select the last checkbox and submit.
Using the last submitted response form data again, render the form and see the output.
### Screenshot - *(optional)*
![image](https://github.com/user-attachments/assets/4184ae0d-8d1a-4c4b-9d34-c53627982593)

**Comment by lucasnetau** [comment]
Please try with the current release version 3.19.13, I was not able to replicate your issue with this release

**Comment by akashvora** [comment]
Hello @lucasnetau, 
Thanks for the quick response.
 but still facing the same issue.

**Comment by lucasnetau** [comment]
I am only able to reproduce point 3 `If you select the first checkbox and the third (last) checkbox and submit and render, the last checkbox does not get selected.`

You have not assigned a value to either option 2 or option 3, therefore the value for the checkbox defaults to 'on' for both of them. When saving this data the userData array is not positional if one or more checkboxes is unchecked since they have no value at that time.

The issue here is you have undefined behaviours because you are missing the value attribute for multiple checkboxes of the same name/id. Adding a value will fix this issue. This would also be an issue if you have values being the same value
