### ISSUE TITLE
Dispatched events

### ISSUE THREAD

**Issue by domialex** [kevinchappell/formBuilder#172]
You could dispatch events in the element instead of the document.
`document.dispatchEvent(formBuilder.events.loaded);`
to
`elem.get(0).dispatchEvent(formBuilder.events.loaded);`

**Comment by kevinchappell** [comment]
That's a good point and had considered it but decided to attach them to document since re-initializing would remove references to the created DOM, breaking any listeners.

Does anyone have issue with dispatching events from element instead of document?

**Comment by domialex** [comment]
Where would it break actually? The events are only bound once from what I see.

**Comment by kevinchappell** [comment]
My concern was if a developer adds eventListener to the builder and event is dispatched from builder/element instead of document, if the plug-in is re-initialized the listener will no longer work because the builder is entirely regenerated. The listeners would have to be re-added if the plug-in is re-initialized. 

If developer added eventListener to the document and formBuilder dispatched from element it would still work as long as event bubbles, which it does but then I don't see the advantage of changing the dispatch to the element. 

Just to be clear, I'm not against the change- just want to understand the benefits.

**Comment by domialex** [comment]
In my case I'm using the 'loaded' event. I'm doing:
`$(document).on('loaded', ...`
Which seems dangerous for conflicts. Unless I'm not doing this the right way.

**Comment by kevinchappell** [comment]
You have a point about the `loaded ` event, I worried about that too but no one has reported conflict yet. In next version its changed to `formeoLoaded` to avoid possible conflict. 

Getting back to the original issue, I don't see how changing the binding would cause breaking changes for anyone as long as it bubbles so I'll see about making it sometime this week.

**Comment by kevinchappell** [comment]
going to hold off on changing this as it could have adverse effects for anyone currently using `loaded` event. Happy to revisit this if there are any reported issues though.
