### ISSUE TITLE
Display & Edit saved forms

### ISSUE THREAD

**Issue by blaketan** [kevinchappell/formBuilder#179]
Hi Kevin,

First of I'd like to say thanks for all the hard work! We've been using formBuilder on our production Ruby on Rails application for a few months now, and it has been working splendidly. Right now we have some additional code that handles the parsing and saving of the formBuilder elements to the database via an AJAX call, I'd love to wrap all our code up and implement it as a gem(library) for other Ruby on Rails applications. The only issue impeding progress on that is the editting of saved forms from the database, I was wondering if it would be possible to take a json string with all the form details encoded in it and render it back as an editable form. What approach would you suggest?

**Comment by kevinchappell** [comment]
If you have access to the `window` object you could use JSON.stringify and JSON.parse for saving and loading the xml data. In [this codepen](http://codepen.io/kevinchappell/pen/Vedrqr) try adding some fields, clicking the save button and refreshing the page.

Other than that plugin could probably use a setData() method that would allow saved data to be added to it that way rather than setting textarea value, though I'm not sure if that solves your problem.

**Comment by kevinchappell** [comment]
going to close this as I believe it has been answered. Please check docs for implementation.
