### ISSUE TITLE
not escaping html tags during preview mode

### ISSUE THREAD

**Issue by jamesalvarez** [kevinchappell/formBuilder#215]
It's possible for user to insert scripts etc during the preview mode.

(Line 412 in helpers.js)
  // attrs = _helpers.escapeAttrs(attrs);

Was there any reason to comment this line?

**Comment by kevinchappell** [comment]
Good catch, there was no good reason for commenting out the line, it should have been removed. escapeAttrs will now cause malformed html since [the removal](https://github.com/kevinchappell/formBuilder/pull/211/commits/a86fb481300d18b418df0da25584052025133ac9#diff-5058f3eb3ac0b3878e5f0849c3953292R252) of `HTML_ENTITIES`

see [video](https://www.youtube.com/watch?v=wh6Euqe3Gmk)
