### ISSUE TITLE
Feature request: Hide input fields based on values of other input fields

### ISSUE THREAD

**Issue by paulgovers** [kevinchappell/formBuilder#384]
Hi,

input fields are sometimes only usefull when some checkboxes are checked, if not checked some fields could be hidden.
would it be a nice feature to hide input fields based on values of other input fields?

for example:
question1: checkbox "do you eat meat?"
question2: Textbox "how much?"

you can skip question2 if you did not checked question1

Greetings
Paul

**Comment by kevinchappell** [comment]
This is already sort of possible with `typeUserEvents`. The demo [here](http://codepen.io/kevinchappell/pen/vXkKad) can be adapted for entire fields rather than just their attributes.

Unfortunately formRender does have support for conditional fields, the above demo is only applicable to the editor.
