### ISSUE TITLE
When will 2.0 be available?

### ISSUE THREAD

**Issue by wizaerd** [kevinchappell/formBuilder#402]
And will it be available here?  And what is the best place to check out Formeo?  Did you recently change the GitHub location because my saved link doesn't seem to work anymore.

**Comment by nk-nareshkumar** [comment]
Hi, you can find formeo from here. http://draggable.github.io/formeo/

**Comment by wizaerd** [comment]
@nk-nareshkumar Unfortunately, this page you sent is the runnable demo, not the source code repopsitory. If you click the GitHub link in the top right, it goes nowhere...  https://github.com/Draggable/formeo is a dead link.

**Comment by kevinchappell** [comment]
I know previously I said formBuilder 2.0 would be about a week or so but obviously that hasn't happened. In the past I've said I'm not comfortable giving dates and missing them is why.

Formeo repo was made private for 2 reasons: 
1. there was discussion about selling it
2. reduce support time while while finalizing specs

I believe formeo.js should be open-source so it will be but I'd like to keep the repo private until documentation is complete because support time was eating too much dev time. I'll remove the GH link until its available again to reduce confusion.
