### ISSUE TITLE
disableFields doesn't work anymore

### ISSUE THREAD

**Issue by aromka** [kevinchappell/formBuilder#507]
Even if you look at example page - http://formbuilder.readthedocs.io/en/latest/formBuilder/options/disableFields/
`var options = {
    disableFields: [
      'autocomplete',
      'file',
      'date',
      'paragraph'
    ]
  };
  $(fbTemplate).formBuilder(options);`

All those fields still show up

![screenshot at may 29 11-54-42](https://cloud.githubusercontent.com/assets/2651029/26555995/efb22118-4465-11e7-8833-0b9c0c855a91.png)

**Comment by aromka** [comment]
Works in 2.3.3 version, but not after that

**Comment by kevinchappell** [comment]
resolved by #508

**Comment by BrianHVB** [comment]
This issue has reappeared or was never fixed. As of the dist in v2.9.8 disabling fields does not work. I don't think the problem is with, 

https://github.com/kevinchappell/formBuilder/blob/36d4d993252e172d6d77c562564574ed0daec96d/src/js/helpers.js#L751-L754

but I'm not positive as I haven't been able to get the source code to run (only the minified build works).
