### ISSUE TITLE
Content input div "label" does not scroll when data exceeds the vertical limit

### ISSUE THREAD

**Issue by chuckvincent** [kevinchappell/formBuilder#517]
### Description:
First noticed this with Paragraph elements, but happens on several others.  When entering the data for the Paragraph into the Content field, of you exceed the height of the displayed box the text appears under the other input fields and the containing div does not contain all the inputted text and scroll as I would have expected.

### Environment Details:

 - formBuilder Version: 2.5.1
 - Browser: Chrome
 - OS: OSX

### Expected Behavior
containing div for the data for each element would scroll when its height is exceeded.

### Actual Behavior
text overflows past the input box displayed 

### Steps to Reproduce
This currently happens even in the online demo :https://formbuilder.online/ 
1. Drag a Paragraph element to the form builder.
2. Edit the paragraph element
3. Type more data that should fit into the Content input field.

### Screenshot - *(optional)*

![image](https://cloud.githubusercontent.com/assets/2086185/26702847/813f44c0-46ec-11e7-9c71-df9fca62d3f7.png)

**Comment by brentkelly** [comment]
I've noticed this also editing labels for text input etc. It is contenteditable div by default but doesn't expand correctly. 

IMO standard controls shouldn't offer a contenteditable div for the label attribute ideally - as multiline labels are pretty uncommon I would have thought & a number of times I've pasted a label in & not realised that I have pasted in a `<br />` or some other formatting - the UX doesn't lead me to expect that behavior.

For a paragraph we should also consider moving it to use TinyMCE or something perhaps? Or at least allowing the user to specify an option that would do that.

The full (overkill) 'fix' for this bug is giving controls the ability to define their own attributes as outlined in my brainstorming doc here https://goo.gl/baQvUo

**Comment by kevinchappell** [comment]
Adding `overflow-y: auto` to the .fld-label style should be a simple fix in the meantime. Ex:
```
.fld-label {
    min-height: 150px;
    overflow-y: auto;
}
```

**Comment by chuckvincent** [comment]
I have also had a few successful project with textbox.io, to add another option to the WYSIWYG options.

**Comment by brentkelly** [comment]
@chuckvincent yeah textbox.io is nice but its non commercial licencing isn't really compatible with the MIT license for this project.
