### ISSUE TITLE
Single quotes in form label throwing javascript errors on rendering

### ISSUE THREAD

**Issue by CyberFerret** [kevinchappell/formBuilder#529]
### Description:

When you create a form field with a word in single quotes in the editor module, it accepts the data OK, and I can save the resulting JSON into a database.

However, if I was then to use the JSON stream in order to render the form elsewhere, I get an 'invalid token' error and the form does not render.

It appears that the parser is thrown by the single quote character in the JSON data, and it causes a Javascript error.

### Environment Details:

 - formBuilder Version: 2.5.3
 - Browser: Chrome 58.0.3029.110
 - OS: OSX Sierra

### Expected Behavior

I expected the form field prompts to render exactly as they were when I created them.

### Actual Behavior

No form gets rendered at all, and checking the console shows a javascript error highlighting the single quote mark in the JSON data sent to the form render command.

### Steps to Reproduce

Create a form with a text field where the Label contains a quoted string, e.g.:

    If you answered 'Yes' above, then please specify more details below

Save the form as JSON data, then use the same JSON data to render() the form again.

**Comment by KuenzelIT** [comment]
Hey,

I just tested your example and it works in my case. I'm saving the JSON in a MySQL database using PHPs json_encode and json_decode. It just works as expected. Maybe there's something wrong with your JSON saving/parsing?

**Comment by metameister** [comment]
It probably a bit late to reply but for future references...

I was having the same problem as @CyberFerret described.  The fix I found is this:

        options = {
            dataType: 'json',
            showActionButtons: false,
            **formData: JSON.stringify([(your_json_string)]),**
        };

        fb = $(editor).formBuilder(options);

Instead of 
            **formData: '[(your_json_string)]',**

I was thinking about passing the json back using AJAX into formData but this was sufficient to fix the problem.  This is also applicable to formRender().

Another similar tip: use encodeURIComponent() to encode special characters like & < > when sending the form you built to the server backend.
