### ISSUE TITLE
FormBuilder Generates Invalid XML for HTML Controls

### ISSUE THREAD

**Issue by starlightknight** [kevinchappell/formBuilder#530]
### Description:
HTML controls (Header, Paragraph) generate invalid XML. FormBuilder may place ```<br>``` and/or ```<div></div>``` tags as part of its field information, but does *not* escape them when generating XML. This makes the XML invalid, so it fails to parse. If the form is then loaded into FormBuilder again, or FormRender is called on it, they will fail and will render blank.

### Environment Details:

 - formBuilder Version:  2.5.3
 - Browser: Firefox/Chrome
 - OS: Linux

### Expected Behavior

FormBuilder should properly escape the XML it generates. I.e, ```<br> -> &lt;br&gt; or &lt;div&gt;&lt;/div&gt;.``` If properly escaped XML is passed in, FormBuilder loads or renders correctly.

### Actual Behavior

FormBuilder completely fails to consume the XML that it generated, and the XML must be manually fixed.

### Steps to Reproduce

**With sample project:**

1) Download sample: http://www.mediafire.com/file/eswuy52smv5r8hb/Form+Builder+Bug+-+Invalid+XML+Generated.zip

2) Open formbuilder.html

3) Click Log to Console, and see invalid unescaped XML

Note: The invalid HTML tags do not always show up on {}. If the elements are created live, they don't show (in fact, no value shows). If properly escaped XML is loaded, they show. WIth the sample project, I escaped the XML manually that preloads so that it can load for the purposes of demonstration. Either way, bad XML is actually generated.

**Manual Reproduction:**

Open a form builder, add a paragraph control with multiple lines, log HTML to console.

**Comment by ctimmons** [comment]
I've run into the same bug when getting the field definitions as XML.

To reproduce, create a textarea control.  Set its type to "tinymce", and set its value to something like "Hello, world!".  Examine the generated XML with `formBuilder.actions.getData('xml')`.  This can be easily done by using the [interactive demo in the docs](https://formbuilder.readthedocs.io/en/latest/formBuilder/demos/data/), and pressing the "Get XML Data" button.

The `<field>` tag's value attribute will be `value="<p>Hello, world!</p>"`.  This is malformed XML.  It should be `value="&lt;p&gt;Hello, world!&lt;/p&gt;"`.

I believe the bug is in the `utils.markup` function in utils.js.  In the `master` branch, around line 216, this block of code escapes the attribute's name, but not its value:

```javascript
for (let attr in attrs) {
  if (attrs.hasOwnProperty(attr)) {
    let name = utils.safeAttrName(attr)
    field.setAttribute(name, attrs[attr])
  }
}
```

The same lack of escaping is also in the `release/2.10.0` branch:

```javascript
for (let attr in attrs) {
  if (attrs.hasOwnProperty(attr)) {
    const name = utils.safeAttrName(attr)
    const attrVal = Array.isArray(attrs[attr]) ? utils.unique(attrs[attr].join(' ').split(' ')).join(' ') : attrs[attr]
    field.setAttribute(name, attrVal)
  }
}
```

**Comment by andreasotto** [comment]
Any news on this?

formBuilder is not usable as the first attempt using "Test" as a value in a field breaks everything.
