### ISSUE TITLE
Change checkbox default values on its creation

### ISSUE THREAD

**Issue by danielsilverio-dss** [kevinchappell/formBuilder#619]
### Description:

Hi, guys!

Is there a way to change the checkbox default value on it's creation through `typeUserAttrs` or some other configuration?

By default, checkboxes are created with these values:

```
"values": [
			{
				"label": "Option 1",
				"value": "option-1",
				"selected": true
			}
		]

```
However, I wanted to change the `"value": "option-1"` property or, rather, make it empty and put a placeholder instead, which would be better for my purposes.

I've tried including the above structure in typeUserAttrs, only changing the content of `"value"`, and have also tried to use other names instead of `"values"`, such as `"options"`, etc, but none have worked.

I've been able to change all the other kinds of fields, but not this one. Is it possible?

Thanks!

**Comment by eradin** [comment]
I just discovered today (V2.9.8) that there is no way to set the default for a checkbox.  It's always checked.  At a minimum, it should default to unchecked but there should be a way to set the default independently from any others in the group.

Perhaps a solution is to change that radio column in the checkbox options to a checkbox with a title of default.

This is a bug.  The workaround is to use a yes/no radio button pair.

And since we're on this subject, there is no way to reset the radio defaults to none once you select one.  Unless you delete selected item and recreate.  But that's not obvious.

**Comment by jaywelj** [comment]
@kevinchappell same issue to #680 setting default value for the options

**Comment by Jojoshua** [comment]
This can be done with setting user data now
