### ISSUE TITLE
How do you enable the `other` option for select controls?

### ISSUE THREAD

**Issue by shabaz-ejaz** [kevinchappell/formBuilder#626]
I've noticed that checkbox and radio button controls have the ability to enable the `other` option but why doesn't the select dropdown control have this option?

Is there a way I can enable this?
![2017-09-28_11h23_54](https://user-images.githubusercontent.com/29374282/30961937-ca42333e-a43f-11e7-9133-99c5cdbf6534.png)

**Comment by kevinchappell** [comment]
This would require some core changes to get working. I think the problem with this though is that the other option input needs to have the same name as the input it replaces. With a select tag this is tricky because it means copying the select tag name attribute to the other input and changing the select tag name attribute so there are not 2 matching names.

 Would the other value input appear next to the `select`?

**Comment by shabaz-ejaz** [comment]
Yeah I do see the problem, would it not be possible to just replace the options in the resulting json with the value of the `other` field?

Yeah next to the select or more preferably it could appear directly underneath the select.

**Comment by kevinchappell** [comment]
revisiting this, i think a simpler approach would be a custom control

closing as this is quite old now but feel free to reopen
