### ISSUE TITLE
Checkbox Option Value

### ISSUE THREAD

**Issue by robertwong68** [kevinchappell/formBuilder#680]
### Description:
When I add Name and Value pairs to the Option in a Checkbox, I found out I can put the same Value in different rows and will be very confusing. Is there a way to copy the Name to the Value as a default value to minimise error?

### Screenshot - *(optional)*
<img width="593" alt="screenshot 2017-12-21 15 31 23" src="https://user-images.githubusercontent.com/4545068/34246542-12f1411c-e66a-11e7-98c1-3a39c7cc3ea1.png">

**Comment by jaywelj** [comment]
Please help this issue :( i can't find a way to set the name as the default value too.. it would be very helpful for my project :(

**Comment by jaywelj** [comment]
@robertwong68 Have you found a solution with this issue?
@kevinchappell  Please, is there a way for us to do this?

**Comment by kevinchappell** [comment]
I'm not sure I understand the problem. By "Name" do you mean Label? You want it so the Label and Value are the same?
@jaywelj @robertwong68 Can you explain the expected behaviour?

**Comment by jaywelj** [comment]
I'm sorry for causing confusion sir! Yes i meant the option label to match the value.

**Comment by jaywelj** [comment]
@kevinchappell been waiting for a day now, i hope i could know if the function is possible or not. Thank you again

**Comment by kevinchappell** [comment]
@jaywelj I'm still not clear on what is the expected behaviour. These are the options to fix as I understand:
1. User types in the Label and the Value automatically fills with the Label value?
2. Value field is removed and only Label is used as option value?
3. A new button is added that copies the Label field value to Value field?

1 and 2 would introduce breaking changes. 3 would be difficult given the limited space and I have my doubts about how useful the majority of formBuilder users would find such a feature which would mean making it an option that needs to be enabled.

That said, I don't see why this can't be accomplished using the [`typeUserEvents` option](https://formbuilder.readthedocs.io/en/latest/formBuilder/options/typeUserEvents/).
Here is an example that hides the value for checkbox options and uses the label as the value.

https://codepen.io/kevinchappell/pen/oMzKRo

**Comment by kevinchappell** [comment]
@jaywelj did this work for you? if not feel free to reopen

**Comment by jaywelj** [comment]
@kevinchappell Thank you so much for the response!
I've only read your replies just now as i changed track for the mean time because of this problem but i think your example with the checkbox will work in my case., it's just that i'm too noob to understand the codes and make it on my own with typeUserEvents(tried it but 
never figured out it's possible with it). In general though the fix no 1 is the best behavior as it gives a default modifiable value for the users. Thank you again for replying.
