### ISSUE TITLE
radio-group and select problem with options

### ISSUE THREAD

**Issue by MahdiRadcom** [kevinchappell/formBuilder#687]
Adding new option for Select and Radio-Group causes wrong name attribute problem and it ends up with selecting multiple option in FormBuilder.
This is a screenshot of online demo:
![radiobutton issue](https://user-images.githubusercontent.com/30586571/34707961-af0fb6cc-f525-11e7-9a5f-506da9c457aa.png)

I solved the issue by a simple code in selectFieldOptions function in my project but it is a naive way to do that. Would be happy to know your solution:
`while(attrs.name.indexOf('-option-option') != -1)
{
      attrs.name = attrs.name.replace('-option-option', '-option');
}`

**Comment by kevinchappell** [comment]
good find. fix will be in 2.10.0

**Comment by pvin** [comment]
**Observations**

@kevinchappell  any fix in newer version? 

Issue has been raised in [#687](https://github.com/kevinchappell/formBuilder/issues/687) and fixed in release [PR-842](https://github.com/kevinchappell/formBuilder/pull/842#issue-227187787 ) (version - [2.10.0](https://github.com/kevinchappell/formBuilder/pull/842#issue-227187787))

This fix was available till [3.5.2](https://github.com/kevinchappell/formBuilder/releases/tag/v3.5.2) and removed in [3.6.0](https://github.com/kevinchappell/formBuilder/compare/v3.5.2...v3.6.0)

**Fix:**
For time being i'm rolled back to 3.52 by using [CDN](https://cdnjs.com/libraries/jQuery-formBuilder/3.5.2)

**Code reference**
 
![merge-image](https://user-images.githubusercontent.com/4160460/218156180-882f296d-a73d-4c15-88a7-1e4e0f878607.png)
