### ISSUE TITLE
Edit form issue with Radio and check box

### ISSUE THREAD

**Issue by DineeshDS** [kevinchappell/formBuilder#719]
I have created a form and saved as json , When i try to edit the form all field get populated, expect option which i marked as selected in radio and check box. I need to populate the "option selected: true".

I tried this way 
var options = {
          disabledActionButtons: ['data'],
          disableFields: [
              'autocomplete',
              'button',
              'file',
              'header',
              'hidden',
              'paragraph'
          ],
          onSave: function (e, formData){
              $('input[name="formData"]').val(formData);
              $('#question_form').submit();
          },
          defaultFields: JSON.parse(formData)
      };

       $(document.getElementById('fb-editor')).formBuilder(options);

And my json is 
[{"type":"radio-group","label":"Radio Group","values":[{"label":"Option 1"},{"label":"Option 2","selected":"true"},{"label":"Option 3"}]}]
When i render this form Second option not marked as selected.

**Comment by kevinchappell** [comment]
for some reason `selected` is `"true"` instead of `true`, this might be happening because `input[name="formData"]` appears to be used as a buffer. Correcting that got your code working for me.
![image](https://user-images.githubusercontent.com/1457540/47957947-70224400-df7d-11e8-99f5-a175473274f2.png)
