### ISSUE TITLE
Incompatibility issue with IE 9-10

### ISSUE THREAD

**Issue by Karbb** [kevinchappell/formBuilder#756]
### Description:

Internet Explorer v9 / v10 can't render the form.

IE console error: **The object doesnt support the property or the method 'register'**

### Environment Details:

 - formBuilder Version: 2.9.8
 - Browser: IE 9 - 10
 - OS: Windows 10

**Comment by tomvanbrienen** [comment]
+1. Same problem over here. Fix needed.

**Comment by SamuelPelletier** [comment]
I found a solution but it's the worst way to fix it. 
I add in form-builder.min.js and form-render.min.js "try..catch" block around the lines with "register" call function.
This fix work on IE 10, Chrome, Safari and Firefox for sure for render form with json.

The two files is re-write here : https://github.com/SamuelPelletier/fix_form_render

I don't make a pull request because I think is a bad idea my solution but it fix my problem.

**Comment by kevinchappell** [comment]
@SamuelPelletier what line number can I see the fix? The `register` method is a core method for the Control class, if classes are transpiled so should their methods. Can you share more details about the error?

**Comment by SamuelPelletier** [comment]
Line 814 of my re-write file (https://github.com/SamuelPelletier/fix_form_render/blob/master/form-builder.js) : 
try{
     w.default.register(A[e], t, e)
}catch(error){}

I'm sorry for this fix make on mimified file, I have only this source for fix it.

The error is the same as @Karbb said: "The object doesnt support the property or the method 'register'"
This error display in the IE console when we would like render a form.

I have 3 errors : 
SCRIPT438: The object doesnt support the property or the method « register » 
form-builder.min.js, Line 6 Char 203908

SCRIPT438: The object doesnt support the property or the method « register » 
form-render.min.js, Line 6 Char 68850

SCRIPT438: The object doesnt support the property or the method « formRender »

My form render : 
jQuery(function($) {
  var fbRender = document.getElementById('fb-render')

  var formRenderOpts = {
    formData: form,
    dataType: 'xml'
  };

  $(fbRender).formRender(formRenderOpts);
});

This errors are a translate of my french ie browser.
Without my fix this code work on every browser except internet explorer.

**Comment by kevinchappell** [comment]
Babel presets have been adjusted since this issue was first created so this may be resolved. If not it may be resolvable by changing the presets further here: https://github.com/kevinchappell/formBuilder/blob/master/package.json#L65

IE9 and IE10 are no longer supported by formBuilder but if this is still needed I recommend creating a custom build.
