### ISSUE TITLE
Browser Compatibility

### ISSUE THREAD

**Issue by Prince-Garg** [kevinchappell/formBuilder#798]
### Environment Details: Safari browser 5.1.7

 - formBuilder Version: 
 - Browser: Safari
 - OS: HighSierra

**Comment by simon-hevs** [comment]
It works just fine in Safari on a Mac running High Sierra ( Safari Version 11.1.2)
Safari 5.1.7 is the the last Windows version of Safari released in 2012, and is now no longer supported, so I'm not surprised it doesn't run on it.

**Comment by kevinchappell** [comment]
@Prince-Garg Are you sure your OS isn't Windows? I ask because Safari 5.1.7 was released in May of **2012** and was the last version of Safari available for Windows. The current version of Safari for Mac OS is 12.0.1. Given that marketshare for Safari 5.1.7 must be pretty close to 0 and that Apple no longer supports 5.1.7 neither can formBuilder.

That said, formbuilder.online should have a browser support section- I'll add that in the near future.
