### ISSUE TITLE
Save generated form builder data into mysql database

### ISSUE THREAD

**Issue by ralphmallari** [kevinchappell/formBuilder#799]
### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS: 

### Expected Behavior 
First of all, I don't know if this is an issue or if this is the right place to ask, but I want to save the json data into mysql database when the user click the "save" button. And I have no idea how will it be done. Can you help me do it? Or atleast some tutorials or link that can help me. I tried researching but everything I see is not helping me. Thank you.
### Screenshot - *(optional)*

![json](https://user-images.githubusercontent.com/42198726/44437560-52d01180-a5ed-11e8-9f16-0d4af2c86c5b.png)

**Comment by simon-hevs** [comment]
Something like this will do it

            var json = formBuilder.actions.getData('json', true);
            console.log(json);
            $.ajax({
                type: 'POST',
                url: '{your url to save the data to}',
                data: {json: json)},
                success: function () {
                    alert('success')
                },
                error: function () {
                    alert('fail');
                }
            });

**Comment by ralphmallari** [comment]
@simon-hevs @pedromjustino 

Thank you for your answers, both of you. Let me tell you what I'm planning to do right now. So first, I'm putting the json to a variable in js;

`var form_fields = formBuilder.actions.getData('json', true);`

That is the syntax for that right? Next is passing the variable to the php by using ajax, am I saying it right? Because this is where I'm getting confuse;

`$.ajax({
            type: 'POST',
            url: '{your url to save the data to}',
            data: {json: json)},
            success: function () {
                alert('success')
            },
            error: function () {
                alert('fail');
            }
        });`

What does this code do? Is this for the saving the json data to the sql database? Or is it just for the passing of the json data in php?

Again, I'm sorry for all the questions. This are all new to me. Btw, I'm using CakePHP 3.x as my server side  language. Thank you.

**Comment by pedromjustino** [comment]
In your case:
       ```
var form_fields = formBuilder.actions.getData('json', true);
 $.ajax({
            type: 'POST',
            url: '{your url to save the data to}',
            **data: "form_field = "+form_fields,**
            success: function () {
                alert('success')
            },
            error: function () {
                alert('fail');
            }
        });
```

We use it just to send Json Data to PHP. On file .php you send to Mysql database.

**Comment by ralphmallari** [comment]
Okay I think that will do. I will try it tomorrow. Thank you for your inputs. Very much appreciated.

@pedromjustino @simon-hevs

**Comment by petrakid** [comment]
I have a question about this too.

The blue "Save" button at the bottom-right of the form builder doens't seem to do anything.  I added an .on("click",...) method but A) nothing happens and B) the id attribute of the button is different all the time.

In the old version of formBuilder I had to create my own save button and used the id attribute to recognize when it was clicked so the function was fired.  But in this version,...I have no idea how to get the function to recognize that the button is clicked since there's no attribute in the button which makes it distinct from any other element on the page.  I read in another thread that the save button isn't setup to do anything by itself. Then I read in yet another threat that I need to edit the form-builder js file to make the button work, but I use the minified version and there's no way I'm editing it.

I see 
`var form_fields = formBuilder.actions.getData('json', true);`
in a few posts, and this makes sense, but there's nothing here to make this fire...like how is my function supposed to know that I pushed the "save" button to assign the form data to this variable??  This is where I'm sort of stumped...though if I just play more I'll probably figure it out.

**Comment by petrakid** [comment]
Here's what I mean:
```
               var fbTemplate = $('#fb-editor'),
                    options = {    
                         dataType: 'json',
                         formData: data
                    };
               var formBuilder = $(fbTemplate).formBuilder(options);
               $('#button').on('click', function(){
                    var json = formBuilder.actions.getData('json', true);
                    console.log(json);
                    $.ajax({
                         type: 'POST',
                         url: 'my_url',
                         data: {json: json},
                         success: function () {
                              alert('success')
                         },
                         error: function () {
                              alert('fail');
                         }
                    })                    
               })   
```
The on("click") function is supposed to be fired when the blue button is pressed.  But I don't have an id attribute for that button.  HOWEVER, there is a "save-template" class in that button...is that what I should use or is there an easier way to make that button work?
