### ISSUE TITLE
Adding a second textarea to page breaks code

### ISSUE THREAD

**Issue by dannycamps** [kevinchappell/formBuilder#8]
Hello,

I am trying to add additional textareas to the page I am building (using Telerik RadEditors - but a standard HTML textarea exhibits the same behavior).  When I add the textarea, the whole page is thrown off (e.g. form builder controls are repeated, etc...).

Is there anyway around this?

Thanks.
Daniel

**Comment by kevinchappell** [comment]
It sounds like the plugin is being reinitialized. Could you provide a link to the problem in action?

**Comment by dannycamps** [comment]
Sure (and thank you in advance):

Standard Textarea:
https://em.rutgers.edu/checkin/cfe/concept.aspx

Telerik RadEditor (enhanced textarea):
https://em.rutgers.edu/checkin/cfe/concept-2.aspx

**Comment by dannycamps** [comment]
Bah.. right after I sent this - I looked at the code and corrected it using the following to instantiate the form builder:


              jQuery(document).ready(function ($) {
                  'use strict';
                  $(document.getElementById("formBuilder")).formBuilder();
              });

I have some more questions but I will follow-up in another question.

Thanks for the help.
-Daniel

**Comment by kevinchappell** [comment]
From what I see there are 2 `textarea`, the problem comes from your formBuilder selector. RadEditor works similarly to formBuilder in that it starts with a basic textarea then hides.
![image](https://cloud.githubusercontent.com/assets/1457540/10432556/be81cc7e-7103-11e5-9cbd-7754f6c5d916.png)

If you change the formBuilder selector to ... [beat](https://github.com/kevinchappell/formBuilder/issues/8#issuecomment-147448067) me to it.
