### ISSUE TITLE
Lack of consistency in New Radio and Checkbox default strings

### ISSUE THREAD

**Issue by Annuther** [kevinchappell/formBuilder#814]
Hi
When using check boxes or radios the default text is: 
'**Option 1**'   - for the text and  '**option-1**' for the value etc ...
when adding new options using the, 'Add Option +' button; the default strings are: 
'**Label**'   - for the text and  '**Value**' for the value etc ...

Is there any way we can change these default strings so that they are consistent? As they are our non-technical users who already find the concept of form values and text values strange are even more confused by the different default strings here ...

![options-issue](https://user-images.githubusercontent.com/18668429/45635257-6e1f2700-ba9c-11e8-8223-916c9463543a.png)

**Comment by kevinchappell** [comment]
I think there is some confusion between the default values and the placeholders. `Option 1/option-1` are values, `Label/Value` are the placeholders. With `typeUserEvents` options and a little extra code you can merge option and values so users only have to deal with a single field, see: https://codepen.io/kevinchappell/pen/oMzKRo

Would it be helpful if this was a built-in option? What do you suggest for default values instead of Option 1/option-1 pairs?

**Comment by Annuther** [comment]
Hi Kevin,
Yes that fiddle works much better -its what i kind of envisaged. You'd have to ensure that user didnt enter illegal chars as the string entered is going to act as 'Value' and 'Text' - so a custom sanitizer method to strip any chars outside of "a-zA-Z0-9_"  - since the use isn't aware of the 'Value', and its purpose, the whole process is much easier for them. I wish i was more skilled in the J's (script and query) like you guys so i could contribute via the Project - but PHP is my primary tool.

Great Plugin, keep rockin it!!
Cheers.
