### ISSUE TITLE
Laravel Yarn prblem

### ISSUE THREAD

**Issue by JuanAdamuz** [kevinchappell/formBuilder#876]
I have installed the package in laravel as the website says but when I try to edit the icons because i see them as squares, it says font is not a yarn command :/

> yarn font edit
yarn run v1.12.3
error Command "font" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Is tehre a way to manually replace the icons with the font awesome ones?

**Comment by kevinchappell** [comment]
> Is there a way to manually replace the icons with the font awesome ones?

There is but really not recommended because it requires copying and pasting into the src/ directory.
![image](https://user-images.githubusercontent.com/1457540/48956963-aa428e00-ef0a-11e8-979d-5e997076d540.png)

I just double checked and the command worked for me, can you verify you're in the right directory?
