### ISSUE TITLE
Send the xml data to database then getting error 

### ISSUE THREAD

**Issue by dreldrel** [kevinchappell/formBuilder#928]
### Description:
Hey guys, I try to create a button sending the XML data to the database by ajax. But I always get the error and can't figure out the problem. 

The first method is I use the relative position to transmit the data to submit.php, and then I get error which said "vendor.js:9600 POST http://localhost:8080/submit.php 404 (Not Found)". 

The second is I use absolute position to transmit the data, but I still get the error said "Access to XMLHttpRequest at 'file:///C:/Users/Tony/Desktop/form-builder/src/demo/submit.php' from origin 'http://localhost:8080' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https."

Could anyone help me to fix it? As follow is my code and the file position. Thanks!!!

### Environment Details:

 - formBuilder Version: 3.1.3
 - Browser: 
 - OS: Win 10

### Expected Behavior
The XML send to submit successfully the submitting to the MySQL database 

### Actual Behavior
Get 2 types of error
1. vendor.js:9600 POST http://localhost:8080/submit.php 404 (Not Found)
2. Access to XMLHttpRequest at 'file:///C:/Users/Tony/Desktop/form-builder/src/demo/submit.php' from origin 'http://localhost:8080' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
### Screenshot - *(optional)*
![image](https://user-images.githubusercontent.com/45089360/55391516-1a71b800-556c-11e9-93cd-492f54f9b8cd.png)

**Comment by kevinchappell** [comment]
There are a few issues here but this is not a formBuilder bug. 

1. The issue is explained in the error: ` Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.`. Your POST is to `file:///C:/Users/Tony/Desktop/form-builder/src/demo/submit.php` and the local `file://` protocol will not handle the request and CORS policies will block it since it appears to be a different domain. I would recommend `http://localhost:8080/submit.php` instead but...

2. You're using the formBuilder dev server which won't handle php files. You'll need to either setup a devServer proxy or make requests directly to the nginx or apache server for your project.
