### ISSUE TITLE
How to fetch value from the render form in angular

### ISSUE THREAD

**Issue by ronak8532** [kevinchappell/formBuilder#948]
### Description:

I have successful render the form out of json which i have save in database now if user enter data in fields then i want to save the value in that json so is it possible like when i click on submit button then rendered form return json with value which i have enterd. If this is not possible then please guide me how can i save value from the rendered form.

I don't know how to use userData here i am going to mention which i have tried
 
this.formRender = (<any>jQuery('.fb-render')).formRender({ formData });
 window.alert((<any>jQuery('.fb-render')).formRender("userData"));

with this approch i am getting undefined error.

**Comment by kevinchappell** [comment]
since you are assigning the instance to a variable you should be able to call `this.formRender.userData` but for the alert to work you would need to stringing the data. https://formbuilder.online/docs/formRender/actions/userData/

Can you [create a codepen](https://codepen.io/kevinchappell/pen/vLjOLL?editors=1010) that demonstrates the problem?
