### ISSUE TITLE
templates API fieldData properties loss

### ISSUE THREAD

**Issue by Zulkifilyusuf750** [kevinchappell/formBuilder#995]
### Description:
```
let templates = {
  'gps-coords': function(fieldData) {
    console.log(fieldData);
    };
  }
};
```
The **fieldData**.required, fD.title, fD.description, fD.className properties get loss, and are always undefined in a template (or custom type).
### Environment Details:

 - formBuilder Version: 3.2.5
 - Browser: Chrome
 - OS: Windows 10

### Expected Behavior
fieldData properties to be set on field add & field edit.
### Actual Behavior
Some properties of fieldData are always undefined (only set in rawConfig property).
### Screenshot - *(optional)*
![2019-09-14 20_18_27-Greenshot](https://user-images.githubusercontent.com/20576428/65901203-9def5300-e3af-11e9-8440-d37fffcdb574.png)

**Comment by lucasnetau** [comment]
Currently these are the properties that a custom control are given access to. title and description are part of the list 

https://github.com/kevinchappell/formBuilder/blob/27abe220d4dabe8d08a2ab64c28d8e98a986854f/src/js/control/custom.js#L125-L135

**Comment by emirdeliz** [comment]
@lucasnetau I have the same problem here. 

```javascript
const customFormTemplates = {
  custom: function (fieldData) {

    console.log({ fieldData });
  
    const { placeholder, className, name, fieldType } = fieldData;
    return {
      field: `
        <input
          type="text"
          class="form-control ${className || ''}"
          placeholder="${placeholder || ''}"
          name="${name || ''}"
          id="${fieldData.name}"
          fieldType="${fieldType}"
          readonly
        />
      `,
    };
  },
```

The console.log always displays undefined for the required.

**Comment by lucasnetau** [comment]
@emirdeliz, this is as designed (as far as I can tell going through the code) required is removed in formBuilder when rendering the preview to stop the required attribute being set on the inputs, however the preview will still show the required asterisk * and formRender will still render the custom template correctly

https://github.com/kevinchappell/formBuilder/blob/64dfde5961d867d8ac4156eb967b95b3af94d675/src/js/control.js#L23-L25

The only issue I've found so far is that isPreview is in the fieldData object but is always empty because of this line
https://github.com/kevinchappell/formBuilder/blob/64dfde5961d867d8ac4156eb967b95b3af94d675/src/js/control.js#L22

and is therefore not able to be set in custom.js because it doesn't exist. 
https://github.com/kevinchappell/formBuilder/blob/64dfde5961d867d8ac4156eb967b95b3af94d675/src/js/control/custom.js#L131-L139
custom.js should be setting isPreview off the value of this.preview
